# -*- coding: utf-8 -*-
"""Internship_worktask2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ad6UK344kw3YsQ76MfEwxJ1zC6egzfHv
"""

import random

def hangman():
    words = ["apple", "banana", "grape", "mango", "peach"]
    chosen_word = random.choice(words)
    guessed_letters = []
    attempts = 6

    print("Welcome to Hangman!")
    print("_ " * len(chosen_word))

    while attempts > 0:
        guess = input("Guess a letter: ").lower()

        if guess in guessed_letters:
            print("You already guessed that letter.")
            continue

        guessed_letters.append(guess)

        if guess in chosen_word:
            print("Good guess!")
        else:
            attempts -= 1
            print(f"Wrong guess. You have {attempts} attempts left.")

        # Display current progress
        display = [letter if letter in guessed_letters else "_" for letter in chosen_word]
        print(" ".join(display))

        if "_" not in display:
            print("Congratulations! You guessed the word.")
            break

    if "_" in display:
        print(f"Game Over! The word was: {chosen_word}")

# Run the game
hangman()